---
title: "R Notebook"
output: html_notebook
---

## Load Libraries
```{r}
library(httr)
library(jsonlite)
library(glue)
library(stringr)

```



## Token Function
```{r}
get_authentication_token <- function(CLIENT_ID, CLIENT_SECRET){
  
  # Get response
  response = POST('https://accounts.spotify.com/api/token',
                  accept_json(),
                  authenticate(CLIENT_ID, CLIENT_SECRET),
                  body = list(grant_type = 'client_credentials'),
                  encode = 'form',
                  verbose())
  
  # Assign authorization token
  auth_token = content(response)$access_token
  
  return(auth_token)
}
```

### Testing Token Access
```{r}

client_id = Sys.getenv('Spotify_client_id')
client_secret = Sys.getenv('Spotify_client_secret')

## Assign token to global to not need inputting it into each function
auth_token <<- get_authentication_token(client_id, client_secret)

```



## Artist name to ID converter
```{r}

get_artist_ID <- function(artist = NA, authentication_token = auth_token) {
  
  if(is.na(artist)) {
    return('No artist string provided.')
  }
  
  print(paste0("Searching artist: ", artist))
  artist <- str_replace_all(artist, ' ', '%20')
  url = glue('https://api.spotify.com/v1/search?q={artist}&type=artist&limit=1')
  
  response <- GET(url, add_headers(Accept = 'application/json', Authorization = paste('Bearer', authentication_token)))
  print(paste0("Search response status: ", response$status))
  
  content <- content(response)$artists$items[[1]]
  
  artist_name <- content$name
  artist_id <- content$id
  artist_popularity <- content$popularity
  artist_genres <- unlist(content$genres)


  if(is.null(artist_id) | class(artist_id)=='try-error') {
        artist_id <- 'Unknown'
        print(paste0("Artist ID: ", artist_id))
        return(NULL)
  }
  
  print("Related Genres: ")
  print(artist_genres)
  
  print(paste("Artist Found: ", artist_name))

  return(data.frame('Artist.name' = c(artist_name),
                    'Artist.ID' = c(artist_id), 
                    'Artist.Popularity' = c(artist_popularity)))
                    #'Genres' = list(c(artist_genres[1]), c(artist_genres[2]))))
}
```


### Testing artist to ID function:
```{r}
get_artist_ID('alt')[2]
```




## Song name to ID converter
```{r}
get_track_ID <- function(track = NA, limit = 5,
                         authentication_token = auth_token) {
  
  if(is.na(track)) {
    return('No artist string provided.')
  }
  
  print(paste0("Searching track: ", track))
  track <- str_replace_all(track, ' ', '%20')
  url = glue('https://api.spotify.com/v1/search?q={track}&type=track&limit={limit}')
  
  response <- GET(url, add_headers(Accept = 'application/json', Authorization = paste('Bearer', authentication_token)))
  print(paste0("Search response status: ", response$status))
  
  content <- content(response)$tracks$items

  if(length(content) == 0){
    print('No tracks found')
    return(NULL)
  }
  
  tracks_found <- data.frame('Track.Name' = '', 'Track.Artist' = '', 'Track.ID' = '', 'Track.Popularity' = '')

  for(item in 1:length(content)) {
        
    track_name <- content[[item]]$name
    artist_list <- content[[item]]$artists
    track_ID <- content[[item]]$id
    track_popularity <- content[[item]]$popularity
    
    artists <- ''
    for(artist in 1:length(artist_list)){
      if(artist == 1){
        artists <- glue('{artist_list[[artist]]$name}')
      } else {
        artists <- glue('{artists}, {artist_list[[artist]]$name}')
      }
    }
      
    if(is.null(track_ID) | class(track_ID)=='try-error') {
      track_ID <- 'Unknown'
    }
      
    tracks_found <- rbind(tracks_found, data.frame(
                          'Track.Name' = track_name,
                          'Track.Artist' = artists,
                          'Track.ID' = track_ID,
                          'Track.Popularity' = track_popularity))
  }
  
  return(tracks_found)
}

```

### Testing song to ID converter
```{r}
get_track_ID('bloodflood')
```


## Primary Song Recomendation Function
```{r}

get_songs <- function(seed_artists, seed_genres, seed_tracks, 
                      authentication_token = auth_token,
                      ## Optional bleow
                      limit=10, market=NA, 
                      min_acousticness=NA, max_acousticness=NA, target_acousticness=NA,
                      min_danceability=NA, max_danceability=NA, target_danceability=NA,
                      min_duration_ms=NA, max_duration_ms=NA, target_duration_ms=NA,
                      min_energy=NA, max_energy=NA, target_energy=NA,
                      min_instrumentalness=NA, max_instrumentalness=NA, target_instrumentalness=NA,
                      min_key=NA, max_key=NA, target_key=NA,
                      min_liveness=NA, max_liveness=NA, target_liveness=NA,
                      min_loudness=NA, max_loudness=NA, target_loudness=NA,
                      min_mode=NA, max_mode=NA, target_mode=NA,
                      min_popularity=NA, max_popularity=NA, target_popularity=NA,
                      min_speechiness=NA, max_speechiness=NA, target_speechiness=NA,
                      min_tempo=NA, max_tempo=NA, target_tempo=NA,
                      min_time_signature=NA, max_time_signature=NA, target_time_signature=NA,
                      min_valence=NA, max_valence=NA, target_valence=NA) {
  temp <- ''
  for(artist in 1:length(seed_artists)){
    if(artist == 1){
      id <- get_artist_ID(seed_artists[artist])[2]
      temp <- glue('{id}')
    } else {
      id <- get_artist_ID(seed_artists[artist])[2]
      temp <- glue('{temp}%2C{id}')
    }
  }

  seed_artists <- temp
  
  temp <- ''
  for(genre in 1:length(seed_genres)){
    
    clean <- str_replace_all(seed_genres[genre], ' ', '%20')
    
    if(genre == 1){
      temp <- clean
    } else {
      temp <- glue('{temp}%2C{clean}')
    }
  }
  seed_genres <- temp

  base_url = 'https://api.spotify.com/v1/recommendations'
  
  query = query_assembler(seed_artists, seed_genres, seed_tracks, limit, market, 
                          min_acousticness, max_acousticness, target_acousticness,
                          min_danceability, max_danceability, target_danceability,
                          min_duration_ms, max_duration_ms, target_duration_ms,
                          min_energy, max_energy, target_energy,
                          min_instrumentalness, max_instrumentalness, target_instrumentalness,
                          min_key, max_key, target_key,
                          min_liveness, max_liveness, target_liveness,
                          min_loudness, max_loudness, target_loudness,
                          min_mode, max_mode, target_mode,
                          min_popularity, max_popularity, target_popularity,
                          min_speechiness, max_speechiness, target_speechiness,
                          min_tempo, max_tempo, target_tempo,
                          min_time_signature, max_time_signature, target_time_signature,
                          min_valence, max_valence, target_valence)
  
  url = paste0(base_url, query)
  
  response <- GET(url, add_headers(Accept = 'application/json',
                                   Authorization = paste('Bearer', authentication_token)))
  
  content <- content(response)$tracks

  if(length(content) == 0){
    print('No tracks found')
    return(NULL)
  }
  
  tracks_found <- data.frame('Track.Name' = '', 'Track.Artist' = '', 'Track.ID' = '', 'Track.Popularity' = '', 'Track.Link' = '')
  
  for(item in 1:length(content)) {
        
    track_name <- content[[item]]$name
    artist_list <- content[[item]]$artists
    track_ID <- content[[item]]$id
    track_popularity <- content[[item]]$popularity
    track_link <- content[[item]]$external_urls$spotify
    
    artists <- ''
    for(artist in 1:length(artist_list)){
      if(artist == 1){
        artists <- glue('{artist_list[[artist]]$name}')
      } else {
        artists <- glue('{artists}, {artist_list[[artist]]$name}')
      }
    }
      
    if(is.null(track_ID) | class(track_ID)=='try-error') {
      track_ID <- 'Unknown'
    }
      
    tracks_found <- rbind(tracks_found, data.frame(
                          'Track.Name' = track_name,
                          'Track.Artist' = artists,
                          'Track.ID' = track_ID,
                          'Track.Popularity' = track_popularity,
                          'Track.Link' = track_link))
  }
  return(tracks_found)
}


```


## Query formatter for API
```{r}
query_assembler <- function(seed_artists, seed_genres, seed_tracks, limit, market, 
                            min_acousticness, max_acousticness, target_acousticness,
                            min_danceability, max_danceability, target_danceability,
                            min_duration_ms, max_duration_ms, target_duration_ms,
                            min_energy, max_energy, target_energy,
                            min_instrumentalness, max_instrumentalness, target_instrumentalness,
                            min_key, max_key, target_key,
                            min_liveness, max_liveness, target_liveness,
                            min_loudness, max_loudness, target_loudness,
                            min_mode, max_mode, target_mode,
                            min_popularity, max_popularity, target_popularity,
                            min_speechiness, max_speechiness, target_speechiness,
                            min_tempo, max_tempo, target_tempo,
                            min_time_signature, max_time_signature, target_time_signature,
                            min_valence, max_valence, target_valence) {
  
  ## CAPTURE ALL VARIABLES IN A DATAFRAME
  arguments <- data.frame(
                  params = c('seed_artists', 'seed_genres', 'seed_tracks', 'limit', 'market', 
                             'min_acousticness', 'max_acousticness', 'target_acousticness',
                             'min_danceability', 'max_danceability', 'target_danceability',
                             'min_duration_ms', 'max_duration_ms', 'target_duration_ms',
                             'min_energy', 'max_energy', 'target_energy',
                             'min_instrumentalness', 'max_instrumentalness', 'target_instrumentalness',
                             'min_key', 'max_key', 'target_key',
                             'min_liveness', 'max_liveness', 'target_liveness',
                             'min_loudness', 'max_loudness', 'target_loudness',
                             'min_mode', 'max_mode', 'target_mode',
                             'min_popularity', 'max_popularity', 'target_popularity',
                             'min_speechiness', 'max_speechiness', 'target_speechiness',
                             'min_tempo', 'max_tempo', 'target_tempo',
                             'min_time_signature', 'max_time_signature', 'target_time_signature',
                             'min_valence', 'max_valence', 'target_valence'),
                  vals = c(seed_artists, seed_genres, seed_tracks, limit, market, 
                              min_acousticness, max_acousticness, target_acousticness,
                              min_danceability, max_danceability, target_danceability,
                              min_duration_ms, max_duration_ms, target_duration_ms,
                              min_energy, max_energy, target_energy,
                              min_instrumentalness, max_instrumentalness, target_instrumentalness,
                              min_key, max_key, target_key,
                              min_liveness, max_liveness, target_liveness,
                              min_loudness, max_loudness, target_loudness,
                              min_mode, max_mode, target_mode,
                              min_popularity, max_popularity, target_popularity,
                              min_speechiness, max_speechiness, target_speechiness,
                              min_tempo, max_tempo, target_tempo,
                              min_time_signature, max_time_signature, target_time_signature,
                              min_valence, max_valence, target_valence))

  ## FILTER OUT UNSPECIFIED ARGUMENTS
  specified_args <- na.omit(arguments)
  
  ## FORMAT THE BLANKS ///  var --> 'var={var}&' /// except the last var to --> 'var={var}'
  formatted_args <- NA
  for(i in 1:nrow(specified_args)){
    if (i==1){
      formatted_args[[i]] <- glue('?{specified_args[i,1]}={specified_args[i,2]}')
    } else {
      formatted_args[[i]] <- glue('&{specified_args[i,1]}={specified_args[i,2]}')
    }
  }
  
  ## CONCATENATE SPECIFIED VALUE LIST
  assembled_query <- do.call(paste, c(as.list(formatted_args), sep = ""))
  
  ## RETURN ASSEMBLED QUERY
  return (assembled_query)
}

```


### Testing Song recommender
```{r}

## Find song IDs
#get_track_ID('light of the seven')

## Input Artist, Genre, and track ID parameters to give song recommendations
get_songs('BTS', c('edm'), '1SbsbLsUMnAKWHx1zAV6ER')


```

