---
title: "Project Notebook"
author: "Eric Baxter"
date: "12/02/2021"
output: html_document
---

## Feb 3 2021

Had a meeting with the group to discuss project ideas. We looked at API's, and after a few hours settled on the Spotify API and each members assigned functions.


## Feb 12 2021

- Wrote function to get artist info from a name or Spotify Id.
- Wrote function to get song info from a name or Spotify Id.
- Wrote function to get related artists given a Spotify Id.
- Wrote function to get an artists top songs given a Spotify Id.
- Figured out unit tests and implemented on my code.

## Feb 13 2021

- Wrote documentation file.
- Altered `getTopSongs` function to optionally return a graphic.
- Compiled all functions into one `EricsFunctions.R` script, and put my examples into `EricsFunctionsExamples.Rmd`. 

## Feb 16 2021

- Created package structure.
- Wrote roxygen documentation.
- Edited my functions to take auth_token from global environment as default.

## Feb 18 2021

- Began merging our files into one finished package on main.
- Wrote a new function to get audio features for a song.
- Finished unittests and got them all to run successfully.
- Added some graphical outputs.
- Wrote DESCRIPTION file.
- Worked on CI.



