---
title: "Project Notebook"
author: "Eric Baxter"
date: "12/02/2021"
output: html_document
---

## Feb 3 2021

- Had a meeting with the group to discuss project ideas. We looked at API's, and after a few hours settled on the Spotify API and each members assigned functions.


## Feb 12 2021

- Wrote function to get artist info from a name or Spotify Id. 
Commit 14501aa05777fcd89e0d75ce2a0df89f4aa386f8

- Wrote function to get song info from a name or Spotify Id.
Commit 14501aa05777fcd89e0d75ce2a0df89f4aa386f8

- Wrote function to get related artists given a Spotify Id.
Commit 14501aa05777fcd89e0d75ce2a0df89f4aa386f8

- Wrote function to get an artists top songs given a Spotify Id.
Commit 14501aa05777fcd89e0d75ce2a0df89f4aa386f8

- Figured out unit tests and implemented on my code.
Commit 7fc6ed6d8704b2e9df73f92848e88ca99d3d56cb

## Feb 13 2021

- Wrote documentation file.
Commit 97620e25c079e7910ea3a3a8f79e01c28ed78df4

- Altered `getTopSongs` function to optionally return a graphic.
Commit 97620e25c079e7910ea3a3a8f79e01c28ed78df4

- Compiled all functions into one `EricsFunctions.R` script, and put my examples into `EricsFunctionsExamples.Rmd`. 
Commit 97620e25c079e7910ea3a3a8f79e01c28ed78df4

- Tried to make sense of CI
Commits 02634a1a4fd2a351eb39dbe539a5d8b400f36b8a through 2185dbb4ba72bc3cd905a11140aab12d7a3eb3c2

## Feb 16 2021

- Created package structure.
Commit 10f649d681b60185f9d9756a7483f5eb59176e2e

- Wrote roxygen documentation.
Commit f8ca132a96a50e4ee669bae1100bbf8c9f9cfa8e

- Edited my functions to take auth_token from global environment as default.
Commit 9fab02e28703459a1023a3b8cfa74e7a65958b72

## Feb 18 2021

- Began merging our files into one finished package on main.
Commit 054fe6d372297cfcb6902be7f629d3f6846ee2f3

- Wrote a new function to get audio features for a song.
Commit 054fe6d372297cfcb6902be7f629d3f6846ee2f3

- Finished unittests and got them all to run successfully.
Commit 3bf09682b098a0c21409627efd3d39af2e19278d

- Added some graphical outputs.
Commit 054fe6d372297cfcb6902be7f629d3f6846ee2f3

- Wrote DESCRIPTION file.
Commit 054fe6d372297cfcb6902be7f629d3f6846ee2f3

- Worked on CI.
Commit 197bb3b1b101b6ecf63e50e567ddfb30e332c201

- Wrote the license, code of conduct, and contributions documents
Commit 1487bea5b1cfa1973cc12d78b9b8bcc45d18d741

- Wrote the README.rmd file and built the README.md file
Commit 78c72509d2043a3bfa59ab79e59b1851f240bf8f

## Feb 20 2021

- Added some more error catching functionality to getAudioFeatures
Commit 28491dd84a8e63bb0a3daf2160bc9eb459a842be

- Edited vignettes and `README.rmd`
Commit 28491dd84a8e63bb0a3daf2160bc9eb459a842be

- Edited `contributions.md`
Commit 28491dd84a8e63bb0a3daf2160bc9eb459a842be

- Proofread everything for typos
Commit 42bd538f26c959aa7d64a0d238409ac793600cb6

## Feb 21 2021

- Further proofreading and made language of written documents parallel.

- Upload to CRAN.
